version: "3.7"
services:
  docker-in-docker:
    image: docker:dind
    privileged: true
    expose:
      - 2375
      - 2376
    environment:
      DOCKER_TLS_CERTDIR: ""

  anvil:
    build: src/docker
    links:
      - docker-in-docker
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    command: tail -f /dev/null
