name: release

on:
  push:
    tags:
      - "*"
  release:
    types: [prereleased, published]

jobs:
  deliver:
    runs-on: ubuntu-latest
    name: Deliver to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Extract Metadata (tags & labels)
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: saic-oss/anvil
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          file: ./src/docker/Dockerfile
          context: .
          push: true
          tags: saic-oss/anvil:latest
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
