name: release

on:
  push:
    tags:
      - "*"
  release:
    types: [prereleased, published, edited]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run asdf
        uses: asdf-vm/actions/install@v1
      - name: Run hadolint
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./src/docker/Dockerfile
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  test:
    runs-on: ubuntu-latest
    needs: validate
    name: Build Docker Image and Run Unit Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Setup Task
        uses: arduino/setup-task@v1
      - name: Build the Docker Image
        run: task build TAG=local
      - name: Run Unit Tests
        run: task test TAG=local

  deliver:
    runs-on: ubuntu-latest
    needs: test
    name: Deliver to Docker Hub
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Extract Metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: saic-oss/anvil
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
