name: release

on:
  # push:
  #   tags:
  #     - "*"
  release:
    types: [published]

jobs:
  deliver:
    runs-on: ubuntu-latest
    name: Deliver to Docker Hub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # - name: Log in to Docker Hub Manually
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #   run: |
      #     docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
      - name: Extract Metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: saicoss/anvil
      - name: Build and Push to Dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/docker/Dockerfile
          push: true
          # tags: saicoss/anvil:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      # - name: Build the Docker Image
      #   run: docker build -t saicoss/anvil:0.17.0 -f ./src/docker/Dockerfile .
      # - name: Push to Docker Hub
      #   run: docker push saicoss/anvil:0.17.0
