name: unit-test

on: [push, pull_request]

jobs:
  validate:
    runs-on: macos-latest
    name: Validating project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/install@v1
      # - name: Install Task
      #   uses: arduino/setup-task@v1
      # - name: Install pre-commit
      #   uses: pre-commit/action@v2.0.3
      # - name: Validating
      #   run: task validate

  build:
    runs-on: macos-latest
    needs: validate
    name: Build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        uses: ./.github/actions/unit-test-action.yml

  # test:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Run unit tests
  #       run: shellspec

  # secure:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   name: Running automated security checks
  #   steps:
  #     - name: Install dependencies
  #       run: asdf install
  #     - name: Security checks
  #       run: task secure
