name: unit-test

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validating project
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install asdf
        uses: asdf-vm/actions/install@v1
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Install pre-commit
        uses: pre-commit/action@v2.0.3
      - name: Install hadolint
        uses: hadolint/hadolint-action@v1.5.0
      - name: Validating
        run: task validate

  build:
    runs-on: ubuntu-latest
    needs: validate
    name: Build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Build the Docker image
        uses: ./.github/actions/

  test:
    runs-on: ubuntu-latest
    needs: build
    name: Run Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Run unit tests
        run: task test TAG=latest

  # secure:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   name: Running automated security checks
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install asdf
  #       uses: asdf-vm/actions/install@v1
  #     - name: Install Task
  #       uses: arduino/setup-task@v1
  #     - name: Security checks
  #       run: task secure
