name: Unit Test

on: push, pull_request

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validating project
    steps:
      - name: Install dependencies
        run: asdf install
      - name: Validate
        run: task validate

  build:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the Docker image
        uses: ./.github/actions/unit-test-action.yml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run unit tests
        run: shellspec

  secure:
    runs-on: ubuntu-latest
    name: Running automated security checks
    steps:
      - name: Install dependencies
        run: asdf install
      - name: Security checks
        run: task secure
